import { Inter } from "next/font/google";
import "./globals.css";
import Nawbar from "@/app/Nawbar/Nawbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <Nawbar />
        {children}
        </body>
        </html>
    );
}
